export type SeriesFormat = "series" | "miniseries" | "limited" | "anthology";

export type CanonSeries = {
  title: string;
  creator: string;          // showrunner or primary creator
  network: string;          // first/primary home
  yearStart: number;
  yearEnd: number | null;   // null = ongoing
  format: SeriesFormat;
  seasons: number;
  genres: string[];         // controlled vocabulary below
  note: string;             // Jason's one-line curator note
  bestSeason?: number;
  bestEpisode?: { season: number; episode: number; title: string };
};

// Pilot Light — TV Series curated by Jason Chletsos.
// "The pilot is the spark; everything that follows is the burn."
//
// Note voice: evocative one-liner. Edit anything that doesn't sound like you.

export const series: CanonSeries[] = [
  {
    title: "Rectify",
    creator: "Ray McKinnon",
    network: "Sundance",
    yearStart: 2013, yearEnd: 2016,
    format: "series",
    seasons: 4,
    genres: ["drama", "prestige"],
    note: "Daniel Holden walks out of death row into a world that won't quite take him back. The slowest grace on television; nothing else moves at this tempo.",
    bestSeason: 2,
  },
  {
    title: "Band of Brothers",
    creator: "Erik Jendresen & Tom Hanks",
    network: "HBO",
    yearStart: 2001, yearEnd: 2001,
    format: "miniseries",
    seasons: 1,
    genres: ["war", "drama", "miniseries"],
    note: "Easy Company from Toccoa to Berchtesgaden. The miniseries that made every prestige war story afterward look small.",
    bestEpisode: { season: 1, episode: 6, title: "Bastogne" },
  },
  {
    title: "The Shield",
    creator: "Shawn Ryan",
    network: "FX",
    yearStart: 2002, yearEnd: 2008,
    format: "series",
    seasons: 7,
    genres: ["crime", "drama"],
    note: "Vic Mackey on the LA strike team — the antihero pilot that taught FX it could fight HBO. Ends with the only finale that ever quite worked.",
    bestSeason: 5,
  },
  {
    title: "John from Cincinnati",
    creator: "David Milch & Kem Nunn",
    network: "HBO",
    yearStart: 2007, yearEnd: 2007,
    format: "series",
    seasons: 1,
    genres: ["drama", "mystery"],
    note: "Milch's surfer parable after Deadwood. Cancelled in one season, divisive forever; the kind of show only one person could ever have made.",
  },
  {
    title: "Arrested Development",
    creator: "Mitchell Hurwitz",
    network: "Fox / Netflix",
    yearStart: 2003, yearEnd: 2019,
    format: "series",
    seasons: 5,
    genres: ["comedy", "dark-comedy"],
    note: "The Bluth family in disgrace, structured like a sitcom and edited like a thesis. Almost no one watched it in time; everyone has now.",
    bestSeason: 2,
  },
  {
    title: "Gangs of London",
    creator: "Gareth Evans & Matt Flannery",
    network: "Sky / AMC+",
    yearStart: 2020, yearEnd: null,
    format: "series",
    seasons: 3,
    genres: ["crime", "action"],
    note: "What if a London gang epic was directed by the Raid guy. Every fight is choreographed like a war crime.",
  },
  {
    title: "Line of Duty",
    creator: "Jed Mercurio",
    network: "BBC",
    yearStart: 2012, yearEnd: 2021,
    format: "series",
    seasons: 6,
    genres: ["crime", "procedural", "mystery"],
    note: "AC-12 against bent coppers. The 20-minute interrogation scenes are the best procedural writing in 21st-century television.",
    bestSeason: 3,
  },
  {
    title: "Luther",
    creator: "Neil Cross",
    network: "BBC",
    yearStart: 2010, yearEnd: 2019,
    format: "series",
    seasons: 5,
    genres: ["crime", "drama", "thriller"],
    note: "Idris Elba as a London DCI with a rage problem and an Alice Morgan problem. The bottle episodes hit harder than most movies.",
  },
  {
    title: "Law & Order",
    creator: "Dick Wolf",
    network: "NBC",
    yearStart: 1990, yearEnd: null,
    format: "series",
    seasons: 23,
    genres: ["procedural", "crime"],
    note: "Ripped from the headlines, twice an hour, three decades running. The franchise template every American procedural since has cribbed from.",
  },
  {
    title: "Law & Order: SVU",
    creator: "Dick Wolf",
    network: "NBC",
    yearStart: 1999, yearEnd: null,
    format: "series",
    seasons: 25,
    genres: ["procedural", "crime"],
    note: "Olivia Benson is now the longest-running primetime character in American television. The thesis is patience.",
  },
  {
    title: "Law & Order: Criminal Intent",
    creator: "Dick Wolf & René Balcer",
    network: "NBC / USA",
    yearStart: 2001, yearEnd: 2011,
    format: "series",
    seasons: 10,
    genres: ["procedural", "crime"],
    note: "Goren and Eames work the deduction angle. Vincent D'Onofrio leaning into doorframes is its own subgenre.",
  },
  {
    title: "Criminal Minds",
    creator: "Jeff Davis",
    network: "CBS",
    yearStart: 2005, yearEnd: null,
    format: "series",
    seasons: 18,
    genres: ["procedural", "crime", "thriller"],
    note: "BAU profiles the worst people in America. Cold opens that hit like short films, every week.",
  },
  {
    title: "The Tunnel",
    creator: "Ben Richards",
    network: "Sky Atlantic / Canal+",
    yearStart: 2013, yearEnd: 2018,
    format: "series",
    seasons: 3,
    genres: ["crime", "mystery", "thriller"],
    note: "Half French, half British, one body cut between them in the Channel Tunnel. The remake that earned its existence.",
  },
  {
    title: "The Newsroom",
    creator: "Aaron Sorkin",
    network: "HBO",
    yearStart: 2012, yearEnd: 2014,
    format: "series",
    seasons: 3,
    genres: ["drama"],
    note: "Sorkin's third-act monologue, in series form. Will McAvoy on air during real news; you either lean in or you tap out by minute four.",
  },
  {
    title: "Louie",
    creator: "Louis C.K.",
    network: "FX",
    yearStart: 2010, yearEnd: 2015,
    format: "series",
    seasons: 5,
    genres: ["comedy", "dark-comedy"],
    note: "Half stand-up set, half short film, all of it one man's voice. Reset what the half-hour could be.",
  },
  {
    title: "The Simpsons",
    creator: "Matt Groening",
    network: "Fox",
    yearStart: 1989, yearEnd: null,
    format: "series",
    seasons: 35,
    genres: ["comedy", "animation"],
    note: "The first ten seasons are the most-quoted scripts in the English language. The rest is the family staying on the air.",
    bestSeason: 5,
  },
  {
    title: "Justified",
    creator: "Graham Yost",
    network: "FX",
    yearStart: 2010, yearEnd: 2015,
    format: "series",
    seasons: 6,
    genres: ["crime", "drama"],
    note: "Raylan Givens, US Marshal, in Harlan. Elmore Leonard's voice ported to TV without losing anything in the move.",
    bestSeason: 2,
  },
  {
    title: "Patriot",
    creator: "Steve Conrad",
    network: "Amazon",
    yearStart: 2015, yearEnd: 2018,
    format: "series",
    seasons: 2,
    genres: ["dark-comedy", "drama", "thriller"],
    note: "John Tavner sings folk songs about his classified work while bungling assassinations across Luxembourg. The funniest spy drama nobody watched.",
  },
  {
    title: "Breaking Bad",
    creator: "Vince Gilligan",
    network: "AMC",
    yearStart: 2008, yearEnd: 2013,
    format: "series",
    seasons: 5,
    genres: ["crime", "drama"],
    note: "Walter White, Mr. Chips to Scarface, one diagnosis at a time. The show that made AMC a network and 'breaking bad' a phrase.",
    bestSeason: 4,
  },
  {
    title: "Picket Fences",
    creator: "David E. Kelley",
    network: "CBS",
    yearStart: 1992, yearEnd: 1996,
    format: "series",
    seasons: 4,
    genres: ["drama", "mystery"],
    note: "Rome, Wisconsin — quietest town in America, strangest weekly docket. Kelley before Kelley became a brand.",
  },
  {
    title: "Better Call Saul",
    creator: "Vince Gilligan & Peter Gould",
    network: "AMC",
    yearStart: 2015, yearEnd: 2022,
    format: "series",
    seasons: 6,
    genres: ["crime", "drama"],
    note: "Jimmy McGill walking the long road to Saul Goodman. Told as tragedy. The prequel that surpassed the parent.",
    bestSeason: 5,
  },
  {
    title: "The Office",
    creator: "Greg Daniels",
    network: "NBC",
    yearStart: 2005, yearEnd: 2013,
    format: "series",
    seasons: 9,
    genres: ["comedy"],
    note: "Dunder Mifflin Scranton — paper company, real grief. Worth the slow start; Pam and Jim do the real work.",
  },
  {
    title: "Psych",
    creator: "Steve Franks",
    network: "USA",
    yearStart: 2006, yearEnd: 2014,
    format: "series",
    seasons: 8,
    genres: ["comedy", "procedural", "mystery"],
    note: "Shawn Spencer fakes psychic powers for the SBPD. References-per-minute champion of the 2000s.",
  },
  {
    title: "Station Eleven",
    creator: "Patrick Somerville",
    network: "HBO Max",
    yearStart: 2021, yearEnd: 2022,
    format: "miniseries",
    seasons: 1,
    genres: ["drama", "sci-fi", "miniseries"],
    note: "A traveling Shakespeare troupe twenty years after a flu wipes out civilization. Made during the pandemic about something larger.",
  },
  {
    title: "Succession",
    creator: "Jesse Armstrong",
    network: "HBO",
    yearStart: 2018, yearEnd: 2023,
    format: "series",
    seasons: 4,
    genres: ["drama", "dark-comedy"],
    note: "Logan Roy's children fight over a media empire while he's still alive enough to watch. The defining workplace tragedy of the decade.",
    bestSeason: 3,
    bestEpisode: { season: 3, episode: 9, title: "All the Bells Say" },
  },
  {
    title: "True Detective",
    creator: "Nic Pizzolatto",
    network: "HBO",
    yearStart: 2014, yearEnd: null,
    format: "anthology",
    seasons: 4,
    genres: ["crime", "drama", "mystery"],
    note: "Pizzolatto and his rotating cast working the corners of America. Season one is its own complete object; the others negotiate.",
    bestSeason: 1,
  },
  {
    title: "The Bureau",
    creator: "Éric Rochant",
    network: "Canal+",
    yearStart: 2015, yearEnd: 2020,
    format: "series",
    seasons: 5,
    genres: ["drama", "thriller"],
    note: "Le Bureau des Légendes — DGSE officers running long-game ops under cover. The most quietly tense spy show ever made.",
  },
  {
    title: "Banshee",
    creator: "Jonathan Tropper & David Schickler",
    network: "Cinemax",
    yearStart: 2013, yearEnd: 2016,
    format: "series",
    seasons: 4,
    genres: ["crime", "action", "thriller"],
    note: "An ex-con takes the dead sheriff's badge in Banshee, PA. Bone-snapping fight choreography on a network nobody knew existed.",
  },
  {
    title: "Barry",
    creator: "Bill Hader & Alec Berg",
    network: "HBO",
    yearStart: 2018, yearEnd: 2023,
    format: "series",
    seasons: 4,
    genres: ["dark-comedy", "drama"],
    note: "Hader as a hitman who'd rather be an actor. Starts as a comedy, ends somewhere much darker.",
    bestSeason: 3,
  },
  {
    title: "Homeland",
    creator: "Howard Gordon & Alex Gansa",
    network: "Showtime",
    yearStart: 2011, yearEnd: 2020,
    format: "series",
    seasons: 8,
    genres: ["drama", "thriller"],
    note: "Carrie Mathison's manic-genius CIA case file. Seasons one and two are essential; later seasons reward patience.",
    bestSeason: 1,
  },
  {
    title: "Six Feet Under",
    creator: "Alan Ball",
    network: "HBO",
    yearStart: 2001, yearEnd: 2005,
    format: "series",
    seasons: 5,
    genres: ["drama"],
    note: "The Fishers run a Los Angeles funeral home and die a little each episode. Closes with the best finale ever filmed.",
    bestSeason: 4,
  },
  {
    title: "Oz",
    creator: "Tom Fontana",
    network: "HBO",
    yearStart: 1997, yearEnd: 2003,
    format: "series",
    seasons: 6,
    genres: ["drama", "crime"],
    note: "The original HBO prison drama — before Sopranos, before any of it. Where prestige television actually started.",
  },
  {
    title: "House",
    creator: "David Shore",
    network: "Fox",
    yearStart: 2004, yearEnd: 2012,
    format: "series",
    seasons: 8,
    genres: ["procedural", "drama", "mystery"],
    note: "Diagnostician with a Vicodin habit and a Sherlock Holmes thesis. The procedural that learned how to repeat itself well.",
  },
  {
    title: "Task",
    creator: "Brad Ingelsby",
    network: "HBO",
    yearStart: 2025, yearEnd: null,
    format: "limited",
    seasons: 1,
    genres: ["drama", "crime"],
    note: "Ingelsby's follow-up to Mare. Mark Ruffalo as an FBI task force agent working a string of armed robberies in the Philadelphia suburbs.",
  },
  {
    title: "Mare of Easttown",
    creator: "Brad Ingelsby",
    network: "HBO",
    yearStart: 2021, yearEnd: 2021,
    format: "limited",
    seasons: 1,
    genres: ["crime", "drama", "miniseries"],
    note: "Kate Winslet works a Delco missing-persons case from a kitchen full of Wawa hoagies. The vape-pen accent is canon.",
  },
  {
    title: "Evil",
    creator: "Robert & Michelle King",
    network: "CBS / Paramount+",
    yearStart: 2019, yearEnd: 2024,
    format: "series",
    seasons: 4,
    genres: ["drama", "mystery", "thriller"],
    note: "A skeptic, a priest-in-training, and a tech contractor investigate church-flagged cases. The Kings' best post-Good Wife work.",
  },
  {
    title: "The Americans",
    creator: "Joe Weisberg & Joel Fields",
    network: "FX",
    yearStart: 2013, yearEnd: 2018,
    format: "series",
    seasons: 6,
    genres: ["drama", "thriller"],
    note: "Two KGB illegals in suburban Reagan-era DC, raising American teenagers and burying handlers. The final episode is the best in the medium.",
    bestSeason: 5,
    bestEpisode: { season: 6, episode: 10, title: "START" },
  },
  {
    title: "The Pitt",
    creator: "R. Scott Gemmill",
    network: "Max",
    yearStart: 2025, yearEnd: null,
    format: "series",
    seasons: 1,
    genres: ["drama"],
    note: "Real-time ER from the Pittsburgh trauma center. Noah Wyle reading the chart again, twenty years on; the ER spiritual sequel nobody asked for and everyone needed.",
  },
  {
    title: "Happy Valley",
    creator: "Sally Wainwright",
    network: "BBC",
    yearStart: 2014, yearEnd: 2023,
    format: "series",
    seasons: 3,
    genres: ["crime", "drama"],
    note: "Sgt. Catherine Cawood polices the West Yorkshire valleys and quietly carries every grief in town. Sarah Lancashire is the show.",
    bestSeason: 1,
  },
  {
    title: "Halt and Catch Fire",
    creator: "Christopher Cantwell & Christopher C. Rogers",
    network: "AMC",
    yearStart: 2014, yearEnd: 2017,
    format: "series",
    seasons: 4,
    genres: ["drama"],
    note: "Texas in the eighties: PC clones, online services, Mosaic. Season one is the prologue; the real show is what Cameron and Donna build after.",
    bestSeason: 2,
  },
  {
    title: "Narcos",
    creator: "Chris Brancato, Carlo Bernard & Doug Miro",
    network: "Netflix",
    yearStart: 2015, yearEnd: 2017,
    format: "series",
    seasons: 3,
    genres: ["crime", "drama"],
    note: "Pablo Escobar's Medellín cartel as seen from a DEA stakeout. The English-Spanish-subtitle handoff is the show's nerve.",
    bestSeason: 2,
  },
  {
    title: "Narcos: Mexico",
    creator: "Eric Newman & Carlo Bernard",
    network: "Netflix",
    yearStart: 2018, yearEnd: 2021,
    format: "series",
    seasons: 3,
    genres: ["crime", "drama"],
    note: "The Guadalajara cartel and the agent who'll spend the rest of his life paying for what he started. Diego Luna carries a haunted register the original never reached.",
  },
  {
    title: "Broadchurch",
    creator: "Chris Chibnall",
    network: "ITV",
    yearStart: 2013, yearEnd: 2017,
    format: "series",
    seasons: 3,
    genres: ["crime", "mystery", "drama"],
    note: "A boy's body on a Dorset beach and the town that closes around it. Tennant and Colman do the most careful procedural work on either side of the Atlantic.",
    bestSeason: 1,
  },
  {
    title: "Fauda",
    creator: "Lior Raz & Avi Issacharoff",
    network: "Yes / Netflix",
    yearStart: 2015, yearEnd: null,
    format: "series",
    seasons: 4,
    genres: ["thriller", "drama", "action"],
    note: "Israeli Mista'arvim — undercover operatives who pass as Palestinian — and the moral wreckage on every side of the work. Hebrew and Arabic, fluent in both.",
  },
  {
    title: "Unforgotten",
    creator: "Chris Lang",
    network: "ITV",
    yearStart: 2015, yearEnd: null,
    format: "series",
    seasons: 5,
    genres: ["crime", "mystery", "procedural"],
    note: "Cold-case bones turn up; a London team works backward through forty years of lives. Nicola Walker's DCI Cassie Stuart is one of the great procedural leads.",
    bestSeason: 1,
  },
  {
    title: "Scott & Bailey",
    creator: "Sally Wainwright & Diane Taylor",
    network: "ITV",
    yearStart: 2011, yearEnd: 2016,
    format: "series",
    seasons: 5,
    genres: ["crime", "procedural", "drama"],
    note: "Two Manchester Met DCs whose working partnership is the show. Wainwright before Happy Valley, with the same ear for women who carry the weight.",
  },
  {
    title: "Vigil",
    creator: "Tom Edge",
    network: "BBC",
    yearStart: 2021, yearEnd: null,
    format: "series",
    seasons: 2,
    genres: ["thriller", "crime", "mystery"],
    note: "DCI Amy Silva investigates a death aboard a Trident submarine in season one and a desert weapons base in season two. Pressurised procedurals; the bottle holds.",
    bestSeason: 1,
  },
  {
    title: "Slow Horses",
    creator: "Will Smith",
    network: "Apple TV+",
    yearStart: 2022, yearEnd: null,
    format: "series",
    seasons: 5,
    genres: ["thriller", "drama", "dark-comedy"],
    note: "Jackson Lamb runs MI5's leper colony out of Slough House. Gary Oldman wearing a coat older than the agents he's torturing. Mick Herron's Slough House on the screen exactly as written.",
    bestSeason: 2,
  },
  {
    title: "For All Mankind",
    creator: "Ronald D. Moore, Ben Nedivi & Matt Wolpert",
    network: "Apple TV+",
    yearStart: 2019, yearEnd: null,
    format: "series",
    seasons: 4,
    genres: ["sci-fi", "drama"],
    note: "Alt-history where the Soviets land on the moon first and the space race never ends. Each season jumps a decade; the calendar is the engine.",
    bestSeason: 2,
  },
  {
    title: "Kingdom",
    creator: "Byron Balasco",
    network: "DirecTV Audience",
    yearStart: 2014, yearEnd: 2017,
    format: "series",
    seasons: 3,
    genres: ["drama", "sports"],
    note: "Frank Grillo runs the Navy St. gym in Venice and a family. The best MMA show ever made because it isn't really about MMA. Aired on a channel nobody had; deserved a channel everybody had.",
    bestSeason: 2,
  },
  {
    title: "Servant",
    creator: "Tony Basgallop",
    network: "Apple TV+",
    yearStart: 2019, yearEnd: 2023,
    format: "series",
    seasons: 4,
    genres: ["mystery", "thriller", "drama"],
    note: "A Philadelphia brownstone, a reborn doll, a nanny who is somehow more. Shyamalan produced; the half-hour episodes are an exercise in held breath.",
  },
  {
    title: "Dope Thief",
    creator: "Peter Craig",
    network: "Apple TV+",
    yearStart: 2025, yearEnd: 2025,
    format: "limited",
    seasons: 1,
    genres: ["crime", "drama"],
    note: "Two Philly hustlers rip drug houses pretending to be DEA, until they rip the wrong one. Brian Tyree Henry and Wagner Moura running on broken nerve.",
  },
  {
    title: "30 Rock",
    creator: "Tina Fey",
    network: "NBC",
    yearStart: 2006, yearEnd: 2013,
    format: "series",
    seasons: 7,
    genres: ["comedy"],
    note: "Liz Lemon runs a sketch show; Jack Donaghy runs the corporation; Tracy and Jenna run amok. Tina Fey's joke-density-per-minute record still stands.",
    bestSeason: 2,
  },
  {
    title: "Lost",
    creator: "J.J. Abrams, Damon Lindelof & Jeffrey Lieber",
    network: "ABC",
    yearStart: 2004, yearEnd: 2010,
    format: "series",
    seasons: 6,
    genres: ["drama", "mystery", "sci-fi"],
    note: "Oceanic 815 goes down in the Pacific. Six years of flashbacks, hatches, smoke monsters, and the longest-running argument in television about whether the ending earned the journey.",
    bestSeason: 1,
  },
  {
    title: "The Handmaid's Tale",
    creator: "Bruce Miller",
    network: "Hulu",
    yearStart: 2017, yearEnd: 2025,
    format: "series",
    seasons: 6,
    genres: ["drama", "sci-fi", "thriller"],
    note: "Margaret Atwood's Gilead, brought forward and made specific. Elisabeth Moss's quiet rage carries the whole thing; the close-ups are the show.",
    bestSeason: 1,
  },
  {
    title: "Mindhunter",
    creator: "Joe Penhall",
    network: "Netflix",
    yearStart: 2017, yearEnd: 2019,
    format: "series",
    seasons: 2,
    genres: ["crime", "drama", "thriller"],
    note: "Two FBI agents in the 1970s talk to imprisoned serial killers and invent the language of behavioral profiling. Fincher's house style on the small screen; ended too soon.",
    bestSeason: 2,
  },
  {
    title: "The Killing",
    creator: "Veena Sud",
    network: "AMC / Netflix",
    yearStart: 2011, yearEnd: 2014,
    format: "series",
    seasons: 4,
    genres: ["crime", "mystery", "drama"],
    note: "Seattle, perpetual rain, one murder stretched across a whole season. Sarah Linden and Stephen Holder do the slow, careful procedural work; the show patient enough to let them.",
    bestSeason: 1,
  },
  {
    title: "The Fall",
    creator: "Allan Cubitt",
    network: "BBC Two",
    yearStart: 2013, yearEnd: 2016,
    format: "series",
    seasons: 3,
    genres: ["crime", "thriller", "drama"],
    note: "Belfast. Gillian Anderson's DSI Stella Gibson hunting Jamie Dornan's killer in plain sight. The cat-and-mouse you can hear breathing.",
    bestSeason: 1,
  },
  {
    title: "Annika",
    creator: "Nick Walker",
    network: "Alibi / PBS",
    yearStart: 2021, yearEnd: 2023,
    format: "series",
    seasons: 2,
    genres: ["crime", "procedural", "mystery"],
    note: "DI Annika Strandhed runs the Marine Homicide Unit out of Glasgow and breaks the fourth wall to walk you through each case. Nicola Walker again; she's the Scottish coast.",
  },
  {
    title: "Goliath",
    creator: "David E. Kelley & Jonathan Shapiro",
    network: "Amazon",
    yearStart: 2016, yearEnd: 2021,
    format: "series",
    seasons: 4,
    genres: ["drama", "crime"],
    note: "Billy Bob Thornton's washed-up Billy McBride takes the cases nobody wants and finds the corruption nobody's looking for. Kelley after Kelley; sharper than the legal shows he used to write.",
    bestSeason: 1,
  },
  {
    title: "Mad Dogs",
    creator: "Shawn Ryan & Cris Cole",
    network: "Amazon",
    yearStart: 2015, yearEnd: 2016,
    format: "series",
    seasons: 1,
    genres: ["dark-comedy", "crime", "thriller"],
    note: "Four middle-aged friends on a Belize vacation; their host turns up dead before lunch. Shawn Ryan's American take on Cris Cole's UK original — ten episodes, no exit.",
  },
  {
    title: "Killing It",
    creator: "Dan Goor & Luke Del Tredici",
    network: "Peacock",
    yearStart: 2022, yearEnd: 2023,
    format: "series",
    seasons: 2,
    genres: ["comedy", "dark-comedy"],
    note: "Craig Robinson hunting invasive Burmese pythons in the Everglades for grant money. Brooklyn Nine-Nine's writers chasing the American Dream by the tail.",
  },
  {
    title: "Gomorrah",
    creator: "Roberto Saviano",
    network: "Sky Italia",
    yearStart: 2014, yearEnd: 2021,
    format: "series",
    seasons: 5,
    genres: ["crime", "drama"],
    note: "Naples and the Camorra families running it. Saviano's reporting turned into the bleakest crime epic in European television. Subtitled and worth every minute.",
    bestSeason: 1,
  },
  {
    title: "The Sopranos",
    creator: "David Chase",
    network: "HBO",
    yearStart: 1999, yearEnd: 2007,
    format: "series",
    seasons: 6,
    genres: ["crime", "drama"],
    note: "Tony Soprano in therapy and at war with everyone he loves. The show that broke television open; the cut to black is still the argument.",
    bestSeason: 5,
    bestEpisode: { season: 5, episode: 12, title: "Long Term Parking" },
  },
];

// ---------------------------------------------------------------------------
// Derived helpers — used by the catalog, stats, and search.
// ---------------------------------------------------------------------------

export const allCreators = Array.from(new Set(series.map((s) => s.creator))).sort();
export const allNetworks = Array.from(new Set(series.map((s) => s.network))).sort();
export const allGenres = Array.from(new Set(series.flatMap((s) => s.genres))).sort();
export const allDecades = Array.from(
  new Set(series.map((s) => Math.floor(s.yearStart / 10) * 10))
).sort();

export function decadeOf(s: CanonSeries): number {
  return Math.floor(s.yearStart / 10) * 10;
}

export function yearLabel(s: CanonSeries): string {
  if (s.yearEnd === null) return `${s.yearStart}–`;
  if (s.yearStart === s.yearEnd) return `${s.yearStart}`;
  return `${s.yearStart}–${s.yearEnd}`;
}

// ---------------------------------------------------------------------------
// Network families — for visual rhythm in the catalog. These are NOT real
// network branding colors; they're a controlled palette of muted earth tones
// that sit next to the amber accent without fighting it.
// ---------------------------------------------------------------------------

export type NetworkFamily =
  | "premium-cable"   // HBO, Showtime, Starz, Cinemax, HBO Max, Max
  | "broadcast"       // NBC, CBS, ABC, Fox
  | "indie-cable"     // FX, AMC, USA, Sundance
  | "streamer"        // Netflix, Apple TV+, Amazon, Peacock, Hulu, Paramount+
  | "uk-euro"         // BBC, ITV, Sky, Canal+, Yes, DirecTV
  | "other";

export const FAMILY_COLORS: Record<NetworkFamily, { color: string; label: string }> = {
  "premium-cable": { color: "#c7b89f", label: "Premium cable" },
  "broadcast":     { color: "#8a8275", label: "Broadcast" },
  "indie-cable":   { color: "#a4582d", label: "Indie cable" },
  "streamer":      { color: "#6a8a82", label: "Streamer" },
  "uk-euro":       { color: "#7a708a", label: "UK / Europe" },
  "other":         { color: "#5d574c", label: "Other" },
};

export function networkFamily(network: string): NetworkFamily {
  if (/\b(HBO|Showtime|Starz|Cinemax|HBO Max|Max)\b/i.test(network)) return "premium-cable";
  if (/\b(NBC|CBS|ABC|Fox)\b/i.test(network)) return "broadcast";
  if (/\b(FX|AMC|USA|Sundance)\b/i.test(network)) return "indie-cable";
  if (/\b(Netflix|Apple TV\+|Amazon|Peacock|Hulu|Paramount\+)\b/i.test(network)) return "streamer";
  if (/\b(BBC|ITV|Sky|Canal\+|Yes|DirecTV|RTÉ|Alibi)\b/i.test(network)) return "uk-euro";
  return "other";
}

export function networkColor(network: string): string {
  return FAMILY_COLORS[networkFamily(network)].color;
}

// Currently-on-air check — used by hero + pilot wall.
export const onAirCount = series.filter((s) => s.yearEnd === null).length;
